//go:build ignore

// Package main dumps operator DefaultHealthRules as TypeScript for the console plugin.
// Run via scripts/generate-health-rule-defaults.sh (do not invoke directly unless go.mod replace is set).
package main

import (
	"fmt"
	"os"
	"regexp"
	"strings"

	flowsv1beta2 "github.com/netobserv/netobserv-operator/api/flowcollector/v1beta2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var regTrim = regexp.MustCompile(`([a-zA-Z])(0[a-zA-Z])+`)

func durationTrimmed(d *metav1.Duration) string {
	if d == nil {
		return ""
	}
	return regTrim.ReplaceAllString(d.Duration.String(), "$1")
}

func modeOrDefault(m flowsv1beta2.HealthRuleMode) string {
	if m == "" {
		return string(flowsv1beta2.ModeAlert)
	}
	return string(m)
}

func tsString(s string) string {
	return fmt.Sprintf("%q", s)
}

func writeThresholdFields(b *strings.Builder, indent string, t flowsv1beta2.HealthRuleThresholds) {
	if t.Info != "" {
		fmt.Fprintf(b, "%sinfo: %s,\n", indent, tsString(t.Info))
	}
	if t.Warning != "" {
		fmt.Fprintf(b, "%swarning: %s,\n", indent, tsString(t.Warning))
	}
	if t.Critical != "" {
		fmt.Fprintf(b, "%scritical: %s,\n", indent, tsString(t.Critical))
	}
}

func formatThresholdsInline(t flowsv1beta2.HealthRuleThresholds) string {
	parts := []string{}
	if t.Info != "" {
		parts = append(parts, fmt.Sprintf("info: %s", tsString(t.Info)))
	}
	if t.Warning != "" {
		parts = append(parts, fmt.Sprintf("warning: %s", tsString(t.Warning)))
	}
	if t.Critical != "" {
		parts = append(parts, fmt.Sprintf("critical: %s", tsString(t.Critical)))
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

func writeVariant(b *strings.Builder, indent string, v flowsv1beta2.HealthRuleVariant) {
	fmt.Fprintf(b, "%s{\n", indent)
	fmt.Fprintf(b, "%s  thresholds: %s", indent, formatThresholdsInline(v.Thresholds))
	hasExtra := v.LowVolumeThreshold != "" || v.GroupBy != "" || v.TrendOffset != nil || v.TrendDuration != nil || v.Mode != nil
	if hasExtra {
		b.WriteString(",\n")
		if v.LowVolumeThreshold != "" {
			fmt.Fprintf(b, "%s  lowVolumeThreshold: %s,\n", indent, tsString(v.LowVolumeThreshold))
		}
		if v.GroupBy != "" {
			fmt.Fprintf(b, "%s  groupBy: %s,\n", indent, tsString(string(v.GroupBy)))
		}
		if off := durationTrimmed(v.TrendOffset); off != "" {
			fmt.Fprintf(b, "%s  trendOffset: %s,\n", indent, tsString(off))
		}
		if dur := durationTrimmed(v.TrendDuration); dur != "" {
			fmt.Fprintf(b, "%s  trendDuration: %s,\n", indent, tsString(dur))
		}
		if v.Mode != nil {
			fmt.Fprintf(b, "%s  mode: %s,\n", indent, tsString(string(*v.Mode)))
		}
		fmt.Fprintf(b, "%s}", indent)
	} else {
		b.WriteString(fmt.Sprintf("\n%s}", indent))
	}
}

func main() {
	var b strings.Builder

	b.WriteString("// Auto-generated by scripts/generate-health-rule-defaults.sh ; DO NOT EDIT.\n")
	b.WriteString("// Source: network-observability-operator api/flowcollector/v1beta2.DefaultHealthRules\n")
	b.WriteString("// Re-run: OPERATOR_PATH=../network-observability-operator ./scripts/generate-health-rule-defaults.sh\n\n")

	b.WriteString("export type VariantFieldPlaceholders = {\n")
	b.WriteString("  critical?: string;\n")
	b.WriteString("  warning?: string;\n")
	b.WriteString("  info?: string;\n")
	b.WriteString("  lowVolumeThreshold?: string;\n")
	b.WriteString("  trendOffset?: string;\n")
	b.WriteString("  trendDuration?: string;\n")
	b.WriteString("};\n\n")

	b.WriteString("export type HealthRuleDefaultVariant = {\n")
	b.WriteString("  thresholds: { info?: string; warning?: string; critical?: string };\n")
	b.WriteString("  lowVolumeThreshold?: string;\n")
	b.WriteString("  groupBy?: string;\n")
	b.WriteString("  trendOffset?: string;\n")
	b.WriteString("  trendDuration?: string;\n")
	b.WriteString("  mode?: 'Alert' | 'Recording';\n")
	b.WriteString("};\n\n")

	b.WriteString("export type HealthRuleDefaultSummary = {\n")
	b.WriteString("  template: string;\n")
	b.WriteString("  /** Effective rule mode (Alert when unset in operator defaults). */\n")
	b.WriteString("  mode: 'Alert' | 'Recording';\n")
	b.WriteString("  /** All default variants for this template (used when customizing). */\n")
	b.WriteString("  variants: HealthRuleDefaultVariant[];\n")
	b.WriteString("};\n\n")

	b.WriteString("/** Default health-rule templates from the operator (name, mode, variants). */\n")
	b.WriteString("export const HEALTH_RULE_DEFAULTS: HealthRuleDefaultSummary[] = [\n")

	for _, rule := range flowsv1beta2.DefaultHealthRules {
		if len(rule.Variants) == 0 {
			fmt.Fprintf(os.Stderr, "default health rule %s has no variants\n", rule.Template)
			os.Exit(1)
		}
		mode := modeOrDefault(rule.Mode)

		fmt.Fprintf(&b, "  {\n")
		fmt.Fprintf(&b, "    template: %s,\n", tsString(string(rule.Template)))
		fmt.Fprintf(&b, "    mode: %s,\n", tsString(mode))
		b.WriteString("    variants: [\n")
		for i, v := range rule.Variants {
			writeVariant(&b, "      ", v)
			if i < len(rule.Variants)-1 {
				b.WriteString(",\n")
			} else {
				b.WriteString("\n")
			}
		}
		b.WriteString("    ]\n")
		b.WriteString("  },\n")
	}
	b.WriteString("];\n\n")

	b.WriteString("/** Primary (first) variant defaults per health-rule template (form placeholders). */\n")
	b.WriteString("export const VARIANT_DEFAULT_PLACEHOLDERS: Record<string, VariantFieldPlaceholders> = {\n")
	for _, rule := range flowsv1beta2.DefaultHealthRules {
		v := rule.Variants[0]
		fmt.Fprintf(&b, "  %s: {\n", rule.Template)
		writeThresholdFields(&b, "    ", v.Thresholds)
		if v.LowVolumeThreshold != "" {
			fmt.Fprintf(&b, "    lowVolumeThreshold: %s,\n", tsString(v.LowVolumeThreshold))
		}
		if off := durationTrimmed(v.TrendOffset); off != "" {
			fmt.Fprintf(&b, "    trendOffset: %s,\n", tsString(off))
		}
		if dur := durationTrimmed(v.TrendDuration); dur != "" {
			fmt.Fprintf(&b, "    trendDuration: %s,\n", tsString(dur))
		}
		b.WriteString("  },\n")
	}
	b.WriteString("};\n\n")

	b.WriteString("export const getVariantPlaceholders = (template?: string): VariantFieldPlaceholders => {\n")
	b.WriteString("  if (!template) {\n")
	b.WriteString("    return {};\n")
	b.WriteString("  }\n")
	b.WriteString("  return VARIANT_DEFAULT_PLACEHOLDERS[template] ?? {};\n")
	b.WriteString("};\n\n")

	b.WriteString("export const getHealthRuleDefault = (template?: string): HealthRuleDefaultSummary | undefined =>\n")
	b.WriteString("  template ? HEALTH_RULE_DEFAULTS.find(d => d.template === template) : undefined;\n\n")

	b.WriteString("/** Convert an operator default into a FlowCollector healthRules entry. */\n")
	b.WriteString("export const healthRuleDefaultToFLP = (def: HealthRuleDefaultSummary): {\n")
	b.WriteString("  template: string;\n")
	b.WriteString("  mode: 'Alert' | 'Recording';\n")
	b.WriteString("  variants: HealthRuleDefaultVariant[];\n")
	b.WriteString("} => ({\n")
	b.WriteString("  template: def.template,\n")
	b.WriteString("  mode: def.mode,\n")
	b.WriteString("  variants: def.variants.map(v => ({\n")
	b.WriteString("    thresholds: { ...v.thresholds },\n")
	b.WriteString("    ...(v.lowVolumeThreshold ? { lowVolumeThreshold: v.lowVolumeThreshold } : {}),\n")
	b.WriteString("    ...(v.groupBy ? { groupBy: v.groupBy } : {}),\n")
	b.WriteString("    ...(v.trendOffset ? { trendOffset: v.trendOffset } : {}),\n")
	b.WriteString("    ...(v.trendDuration ? { trendDuration: v.trendDuration } : {}),\n")
	b.WriteString("    ...(v.mode ? { mode: v.mode } : {})\n")
	b.WriteString("  }))\n")
	b.WriteString("});\n\n")

	b.WriteString("/** Format threshold map for compact UI display (e.g. Manage rules drawer). */\n")
	b.WriteString("export const formatThresholdsSummary = (thresholds?: {\n")
	b.WriteString("  info?: string | number;\n")
	b.WriteString("  warning?: string | number;\n")
	b.WriteString("  critical?: string | number;\n")
	b.WriteString("}): string => {\n")
	b.WriteString("  if (!thresholds) {\n")
	b.WriteString("    return '';\n")
	b.WriteString("  }\n")
	b.WriteString("  const parts: string[] = [];\n")
	b.WriteString("  if (thresholds.info != null && thresholds.info !== '') {\n")
	b.WriteString("    parts.push(`info: ${thresholds.info}`);\n")
	b.WriteString("  }\n")
	b.WriteString("  if (thresholds.warning != null && thresholds.warning !== '') {\n")
	b.WriteString("    parts.push(`warning: ${thresholds.warning}`);\n")
	b.WriteString("  }\n")
	b.WriteString("  if (thresholds.critical != null && thresholds.critical !== '') {\n")
	b.WriteString("    parts.push(`critical: ${thresholds.critical}`);\n")
	b.WriteString("  }\n")
	b.WriteString("  return parts.join(', ');\n")
	b.WriteString("};\n")

	os.Stdout.WriteString(b.String())
}
